services:
    cv:
        image: cv
        build:
            dockerfile: local.Dockerfile
            context: .
            args:
                UID: 1000
                GID: 1000
        container_name: cv
        ports:
            - '94:80'
        volumes:
            - ./:/var/www/html
            - /home/christian/Code/php/pixlstack:/home/christian/Code/php/pixlstack
        environment:
            INI_ZEND_EXTENSION: xdebug.so
            OPCACHE_MAX_WASTED_PERCENTAGE: 20
            OPCACHE_JIT: 1255
            OPCACHE_ENABLE: 1
            OPCACHE_JIT_BUFFER_SIZE: 100M
            OPCACHE_VALIDATE_TIMESTAMPS: 1
            OPCACHE_INTERNED_STRINGS_BUFFER: 16
            XDEBUG_MODE: debug
            XDEBUG_CLIENT_HOST: host.docker.internal
            XDEBUG_START_WITH_REQUEST: yes
            XDEBUG_DISCOVER_CLIENT_HOST: true
